# Generated by Django 5.2.6 on 2025-09-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, help_text='Path under static/, e.g. blog/images/post1.jpg', max_length=255),
        ),
    ]
