# Generated by Django 5.2.6 on 2025-09-09 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/banners/'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='blog.post')),
            ],
        ),
    ]
