# Generated by Django 5.2.6 on 2025-09-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_banner_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog/gallery/thumbs/'),
        ),
    ]
